title: Emmanuel Adeloju
logo: /images/emmanuelAdeloju.jpeg
description: |
  <strong>PhD Student</strong><br>
  ğŸ“ Tempe, AZ<br><br>
  <a href="mailto:eadeloju@asu.edu">Email</a> | 
  <a href="https://drive.google.com/file/d/1XjEAT99_7DPFjQOZW1qFzs9dA-8VHx3Z/view?usp=sharing">Resume</a> | 
  <a href="www.linkedin.com/in/emmanuel-adeloju">LinkedIn</a> |
  <a href="https://github.com/Prodholly">GitHub</a><br><br> 
  <em>Actively seeking collaboration and internship in Human-Centered AI and LLM evaluation</em>
show_downloads: false
theme: jekyll-theme-minimal
