title: Emmanuel Adeloju
logo: /images/emmanuelAdeloju.jpeg
description: |
  <strong>PhD Student</strong><br>
  ğŸ“ Tempe, AZ<br><br>
  <a href="mailto:eadeloju@asu.edu">Email</a> | 
  <a href="/assets/resume.pdf">Resume</a> | 
  <a href="https://linkedin.com/in/emmanueladeloju">LinkedIn</a><br><br>
  <em>Actively seeking collaboration and internships in Human-Centered AI and LLM evaluation</em>
show_downloads: false
theme: jekyll-theme-minimal
